import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  const exercises = ["1", "2", "3", "4"];
  return (
    <div>
      <Head>
        <title>PMT -Advanced-React-Patters</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>List of all the finished exercises</h1>
      <ul>
        {exercises.map((exercise, index) => (
          <li key={`exercises/${exercise}`}>
            <Link  href={`exercises/${exercise}`}>
              <a>{`Exercise no: ${exercise}`}</a>
            </Link>
          </li>
        ))}
      </ul>
     
    </div>
  );
};

export default Home;
